require:
  - standard
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - vendor/bundle/**/*
  NewCops: enable

RSpec/MultipleMemoizedHelpers:
  Max: 12
RSpec/NestedGroups:
  Max: 4
