# frozen_string_literal: true

require_relative "customers/customers_contracts_generator"
require_relative "customers/customers_responses_generator"
require_relative "customers/wallet_links_contracts_generator"
require_relative "customers/wallet_links_responses_generator"
