name: Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby-version: [2.7, 3.0, 3.1]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: StandardRb check for Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
        run: bundle exec standardrb
      - name: Quality check for Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
        run: bundle exec rake quality_check
      - name: Run tests for Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
        run: bundle exec rspec
