name: Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.5' # FIXME is minor version needed?
          - '3.0.4' # FIXME is minor version needed?
          - '3.1.2' # FIXME is minor version needed?

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: StandardRb check
        run: bundle exec standardrb
      - name: Quality check
        run: bundle exec rake quality_check
      - name: Run tests
        run: bundle exec rspec
